"use client"
import Footer from "@/components/footer/footer"
import Header from "@/components/header/header"
import { Provider } from "react-redux"
import './globals.css'

import { persistor, store } from "@/redux/store"
import { usePathname } from "next/navigation"
import { PersistGate } from "redux-persist/integration/react"
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //


  const pathname=usePathname();
  return (
    <html lang="en">
      <body>
      <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        {pathname==="/login"||pathname=="/signup"||pathname.includes("/admin")?<></>:<Header/>}
        {children}
        {pathname==="/login"||pathname=="/signup"||pathname.includes("/admin")?<></>: <Footer/>}
        </PersistGate>
      </Provider>
      </body>
    </html>

  )
}
