"use client"
import { Provider } from "react-redux"
import { store } from "./state/store/store"
import Header from "@/components/header/header"
import Footer from "@/components/footer/footer"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ height: '1000px'}}>
      <Provider store={store}>
        <Header/>
        {children}
        {/* <Footer/> */}
      </Provider>
      </body>
    </html>

  )
}
