"use client"
import './globals.css'
import { Provider } from "react-redux"
import Header from "@/components/header/header"
import Footer from "@/components/footer/footer"
import { store } from "@/redux/store"
import { BrowserRouter as Router } from "react-router-dom"
import dynamic from 'next/dynamic'
import { usePathname } from "next/navigation"
const DynamicHeader = dynamic(() => import("@/components/header/header"), {
  loading: () => <p>Loading...</p>,
})
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //


  const pathname=usePathname();
  return (
    <html lang="en">
      <body>
      <Provider store={store}>
        {pathname==="/login"||pathname=="/signup"?<></>:<DynamicHeader/>}
        {children}
        {/* {pathname==="/login"||pathname=="/signup"?<></>: <Footer/>} */}
      </Provider>
      </body>
    </html>

  )
}
